# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'notebook.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/not/16_122653.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(10, 30, 281, 241))
        self.textEdit.setStyleSheet("background-color: rgb(255, 252, 217);")
        self.textEdit.setObjectName("textEdit")
        self.textEdit_2 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_2.setGeometry(QtCore.QRect(320, 30, 471, 421))
        self.textEdit_2.setStyleSheet("background-color: rgb(188, 254, 255);")
        self.textEdit_2.setObjectName("textEdit_2")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(40, 279, 191, 91))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton_kaydet = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_kaydet.setStyleSheet("background-color: rgb(255, 255, 255);")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/not/diskette_save_saveas_1514.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_kaydet.setIcon(icon1)
        self.pushButton_kaydet.setIconSize(QtCore.QSize(25, 25))
        self.pushButton_kaydet.setObjectName("pushButton_kaydet")
        self.verticalLayout.addWidget(self.pushButton_kaydet)
        self.pushButton_ac = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_ac.setStyleSheet("background-color: rgb(255, 255, 255);")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/not/open-file_40455.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_ac.setIcon(icon2)
        self.pushButton_ac.setIconSize(QtCore.QSize(25, 25))
        self.pushButton_ac.setObjectName("pushButton_ac")
        self.verticalLayout.addWidget(self.pushButton_ac)
        self.pushButton_sil = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_sil.setGeometry(QtCore.QRect(420, 470, 321, 41))
        self.pushButton_sil.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.pushButton_sil.setObjectName("pushButton_sil")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionctrl_s = QtWidgets.QAction(MainWindow)
        self.actionctrl_s.setObjectName("actionctrl_s")
        self.actionA = QtWidgets.QAction(MainWindow)
        self.actionA.setObjectName("actionA")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Notebook"))
        self.pushButton_kaydet.setText(_translate("MainWindow", "Kaydet"))
        self.pushButton_ac.setText(_translate("MainWindow", "Aç"))
        self.pushButton_sil.setText(_translate("MainWindow", "Sil"))
        self.actionctrl_s.setText(_translate("MainWindow", "ctrl+s"))
        self.actionA.setText(_translate("MainWindow", " Aç ctrl+0"))
import ikon_rc
